name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup OCaml
      uses: avsm/setup-ocaml@v1.0
    - name: Install depext module
      run: opam install -y depext
    - name: Use latest ocaml-alsa
      run: git clone https://github.com/savonet/ocaml-alsa.git && opam pin -y add ocaml-alsa
    - name: Pin locally
      run: opam pin -y add --no-action .
    - name: Install locally
      run: opam depext -y -i monadic-synth
    - name: Build locally
      run: eval $(opam env) && dune build
    - name: Run tests locally
      run: eval $(opam env) && dune runtest
